"""
Mark II Studio — ChangeRequest Model
Represents a user comment submitted during the build phase.
"""
from __future__ import annotations

import uuid

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base, TimestampMixin


class ChangeRequest(Base, TimestampMixin):
    __tablename__ = "change_requests"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project_sessions.id"), nullable=False
    )

    # User input
    user_comment: Mapped[str] = mapped_column(Text, nullable=False)

    # Claude classification
    classification: Mapped[str] = mapped_column(
        String(32), default="pending"
    )  # pending | direct_tweak | scope_change | requirement_conflict

    # Structured instruction generated by Claude
    structured_instruction: Mapped[dict] = mapped_column(JSON, default=dict)

    # Status
    status: Mapped[str] = mapped_column(
        String(32), default="pending"
    )  # pending | applied | needs_approval | rejected

    # Relationships
    session = relationship("ProjectSession", back_populates="change_requests")

    def __repr__(self) -> str:
        return f"<ChangeRequest {self.classification} status={self.status}>"
